spring:
  application:
    name: nbc-scheduler
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG